name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  make-protogen:

    runs-on: ghcr.io/streamingfast/substreams

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: make protogen --verbose
  make-build:
    runs-on: ghcr.io/streamingfast/substreams
    needs: make-protogen
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: make build --verbose
