name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ghcr.io/streamingfast/substreams

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: make protogen --verbose
    - name: Run tests
      run: make build --verbose
