name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  make-protogen:
    runs-on: ubuntu-latest                                                                        
    container:                                                                                    
      image: ghcr.io/streamingfast/substreams:latest 

    steps:
    - uses: actions/checkout@v3
    - name: Install buf
      run: |
        set -e
        curl -sSL \
          "https://github.com/bufbuild/buf/releases/latest/download/buf-Linux-x86_64" \
          -o /usr/local/bin/buf
        chmod +x /usr/local/bin/buf
 
    - name: Build
      run: 	|
        set -e
        substreams protogen ./substreams.yaml --exclude-paths="sf/substreams,google"
  make-build:
    runs-on: ubuntu-latest                                                                        
    container:                                                                                    
      image: ghcr.io/streamingfast/substreams:latest 
    needs: make-protogen
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --target wasm32-unknown-unknown --release
